[package]
name = "marco_paspuel_add_one"
version = "0.0.5"
edition = "2021"
description = "Test cargo workpaces publish add one"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
